/**
 * Workspace user key management.
 *
 * A workspace user key is an ephemeral Nostr keypair generated by the client,
 * encrypted to the user's own real npub via NIP-44, and stored as an opaque blob.
 * At runtime the user decrypts this blob once with their real signer, and all
 * subsequent crypto (owner-payload, record signing, NIP-98 API auth) can use the
 * workspace user key from memory.
 *
 * Trust model: user generates key → encrypts to self → server stores ciphertext
 * only → user decrypts at runtime → trust extends to the key.
 */

import {
  clearActiveWorkspaceUserKey,
  createEncryptedWorkspaceUserKeyBlob,
  decryptWorkspaceUserKeyBlob,
  exportWorkspaceUserKeyForWorker as exportLibraryWorkspaceUserKeyForWorker,
  generateWorkspaceUserKey,
  getActiveWorkspaceUserKey,
  getActiveWorkspaceUserKeyNpub,
  getWorkspaceUserKeySecretForAuth as getLibraryWorkspaceUserKeySecretForAuth,
  getWorkspaceUserKeySecretForCrypto,
  isActiveWorkspaceUserKeyRegistered,
  markActiveWorkspaceUserKeyRegistered,
  setActiveWorkspaceUserKey,
} from '@nostr-superbased/browser/workspace-keys';
import { bytesToHex, decodeNsec, generateLocalIdentity } from '@nostr-superbased/core/client';
import { personalEncryptForNpub, personalDecryptFromNpub } from '../auth/nostr.js';
import { getSharedDb } from '../db.js';
import { flightDeckLog } from '../logging.js';

// ---------------------------------------------------------------------------
// Flight Deck compatibility adapters.
// Public function names keep FD's historical "workspace key" API, while
// internals delegate to @nostr-superbased/browser's workspaceUserKey runtime.
// ---------------------------------------------------------------------------

function clean(value) {
  return String(value || '').trim();
}

function firstClean(...values) {
  for (const value of values) {
    const normalized = clean(value);
    if (normalized) return normalized;
  }
  return '';
}

function normalizeEpoch(...values) {
  for (const value of values) {
    if (value === null || value === undefined || value === '') continue;
    const epoch = Number(value);
    if (Number.isFinite(epoch) && epoch > 0) return epoch;
  }
  return 1;
}

function toLibraryWorkspaceUserKey(key, fallback = {}) {
  if (!key) return null;
  const secret = key.secret instanceof Uint8Array ? key.secret : decodeNsec(key.nsec);
  return {
    nsec: key.nsec,
    secret,
    secretHex: firstClean(key.secretHex, bytesToHex(secret)),
    workspaceUserKeyNpub: firstClean(
      key.workspaceUserKeyNpub,
      key.workspace_user_key_npub,
      key.ws_key_npub,
      key.npub,
      fallback.workspaceUserKeyNpub,
      fallback.npub,
    ),
    epoch: normalizeEpoch(
      key.epoch,
      key.workspace_user_key_epoch,
      key.ws_key_epoch,
      fallback.epoch,
    ),
    workspaceServiceNpub: firstClean(
      key.workspaceServiceNpub,
      key.workspace_service_npub,
      key.workspaceOwnerNpub,
      key.workspace_owner_npub,
      fallback.workspaceServiceNpub,
      fallback.workspaceOwnerNpub,
    ),
    userNpub: firstClean(
      key.userNpub,
      key.user_npub,
      key.encrypted_by_npub,
      fallback.userNpub,
      fallback.user_npub,
    ),
  };
}

function toFlightDeckWorkspaceKey(key) {
  if (!key) return null;
  const workspaceUserKeyNpub = firstClean(key.workspaceUserKeyNpub, key.workspace_user_key_npub, key.ws_key_npub, key.npub);
  const workspaceServiceNpub = firstClean(key.workspaceServiceNpub, key.workspace_service_npub, key.workspaceOwnerNpub, key.workspace_owner_npub);
  return {
    nsec: key.nsec,
    npub: workspaceUserKeyNpub,
    secret: key.secret,
    secretHex: key.secretHex,
    epoch: normalizeEpoch(key.epoch, key.workspace_user_key_epoch, key.ws_key_epoch),
    workspaceOwnerNpub: workspaceServiceNpub,
    workspaceServiceNpub,
    workspaceUserKeyNpub,
    userNpub: firstClean(key.userNpub, key.user_npub, key.encrypted_by_npub),
  };
}

function toLibraryWorkspaceUserKeyBlob(blob) {
  if (!blob) return blob;
  const workspaceServiceNpub = firstClean(blob.workspace_service_npub, blob.workspace_owner_npub);
  const workspaceUserKeyNpub = firstClean(blob.workspace_user_key_npub, blob.ws_key_npub);
  const epoch = normalizeEpoch(blob.workspace_user_key_epoch, blob.ws_key_epoch);
  return {
    ...blob,
    workspace_service_npub: workspaceServiceNpub,
    workspace_owner_npub: workspaceServiceNpub,
    workspace_user_key_npub: workspaceUserKeyNpub,
    ws_key_npub: workspaceUserKeyNpub,
    workspace_user_key_epoch: epoch,
    ws_key_epoch: epoch,
  };
}

function toFlightDeckWorkspaceKeyBlob(blob) {
  if (!blob) return blob;
  const normalized = toLibraryWorkspaceUserKeyBlob(blob);
  return {
    ...normalized,
    workspace_owner_npub: normalized.workspace_service_npub,
    ws_key_npub: normalized.workspace_user_key_npub,
    ws_key_epoch: normalized.workspace_user_key_epoch,
  };
}

const realUserNip44Auth = {
  async nip44EncryptToNpub(recipientNpub, plaintext) {
    return personalEncryptForNpub(recipientNpub, plaintext);
  },
  async nip44DecryptFromNpub(senderNpub, ciphertext) {
    return personalDecryptFromNpub(senderNpub, ciphertext);
  },
};

/**
 * Set the active workspace user key after decryption.
 * @param {{ nsec: string, secret: Uint8Array, secretHex: string, npub: string, epoch: number, workspaceOwnerNpub: string }} key
 * @param {{ registered?: boolean }} options
 */
export function setActiveWorkspaceKey(key, options = {}) {
  setActiveWorkspaceUserKey(toLibraryWorkspaceUserKey(key), options);
}

/**
 * Mark the active workspace user key as registered with Tower.
 * Only after this should the key be used for NIP-98 API auth.
 */
export function markWorkspaceKeyRegistered() {
  markActiveWorkspaceUserKeyRegistered();
}

export function isWorkspaceKeyRegistered() {
  return isActiveWorkspaceUserKeyRegistered();
}

export function getActiveWorkspaceKey() {
  return toFlightDeckWorkspaceKey(getActiveWorkspaceUserKey());
}

/**
 * Returns the workspace user key secret for NIP-98 auth,
 * but ONLY if Tower registration has been confirmed.
 * This prevents using the key for API auth before Tower knows about it.
 */
export function getActiveWorkspaceKeySecretForAuth() {
  return getLibraryWorkspaceUserKeySecretForAuth();
}

/**
 * Returns the workspace user key secret for local crypto (owner-payload encrypt/decrypt).
 * Available regardless of registration status — local crypto doesn't need Tower.
 */
export function getActiveWorkspaceKeySecret() {
  return getWorkspaceUserKeySecretForCrypto();
}

export function getActiveWorkspaceKeyNpub() {
  return getActiveWorkspaceUserKeyNpub();
}

export function clearActiveWorkspaceKey() {
  clearActiveWorkspaceUserKey();
}

/**
 * Export the active workspace user key for transfer to the Web Worker.
 * Returns a plain serializable object or null.
 */
export function exportWorkspaceKeyForWorker() {
  const payload = exportLibraryWorkspaceUserKeyForWorker();
  if (!payload) return null;
  return {
    nsec: payload.nsec,
    npub: payload.workspaceUserKeyNpub,
    workspaceUserKeyNpub: payload.workspaceUserKeyNpub,
    epoch: payload.epoch,
    workspaceOwnerNpub: payload.workspaceServiceNpub,
    workspaceServiceNpub: payload.workspaceServiceNpub,
    userNpub: payload.userNpub,
    registered: payload.registered,
  };
}

/**
 * Import a workspace user key from the main thread (used in the worker).
 * Accepts the serializable object from exportWorkspaceKeyForWorker().
 */
export function importWorkspaceKeyFromMain(data) {
  if (!data?.nsec || !(data?.npub || data?.workspaceUserKeyNpub || data?.workspace_user_key_npub || data?.ws_key_npub)) {
    clearActiveWorkspaceUserKey();
    return;
  }
  setActiveWorkspaceUserKey(toLibraryWorkspaceUserKey(data), { registered: Boolean(data.registered) });
}

// ---------------------------------------------------------------------------
// Key generation
// ---------------------------------------------------------------------------

/**
 * Generate a new workspace user keypair.
 * Returns { nsec, npub, secret, secretHex }.
 */
export function generateWorkspaceSessionKey() {
  const identity = generateLocalIdentity();
  return {
    nsec: identity.nsec,
    npub: identity.npub,
    secret: identity.secret,
    secretHex: identity.secretHex,
  };
}

// ---------------------------------------------------------------------------
// Encrypted blob — create, store, retrieve, decrypt
// ---------------------------------------------------------------------------

/**
 * Create the encrypted blob envelope for a workspace user key.
 * Encrypts the nsec to the user's own real npub via NIP-44.
 */
export async function createEncryptedKeyBlob({
  wsKeyNsec,
  wsKeyNpub,
  wsKeyEpoch = 1,
  workspaceOwnerNpub,
  userNpub,
}) {
  const blob = await createEncryptedWorkspaceUserKeyBlob({
    auth: realUserNip44Auth,
    workspaceServiceNpub: workspaceOwnerNpub,
    userNpub,
    workspaceUserKeyNsec: wsKeyNsec,
    workspaceUserKeyNpub: wsKeyNpub,
    epoch: wsKeyEpoch,
  });
  return toFlightDeckWorkspaceKeyBlob(blob);
}

/**
 * Decrypt a workspace user key from its encrypted blob.
 * Returns { nsec, npub, secret, secretHex, epoch, workspaceOwnerNpub }.
 */
export async function decryptKeyBlob(blob) {
  if (!blob?.encrypted_nsec || !blob?.encrypted_by_npub) {
    throw new Error('Invalid workspace user key blob: missing encrypted_nsec or encrypted_by_npub');
  }
  const key = await decryptWorkspaceUserKeyBlob(
    toLibraryWorkspaceUserKeyBlob(blob),
    realUserNip44Auth,
  );
  return toFlightDeckWorkspaceKey(key);
}

// ---------------------------------------------------------------------------
// IndexedDB cache — workspace_keys table in shared DB
// ---------------------------------------------------------------------------

function wsKeysTable() {
  return getSharedDb().workspace_keys;
}

/**
 * Cache an encrypted workspace user key blob in IndexedDB.
 * @param {object} blob - The encrypted key envelope
 * @param {{ registered?: boolean }} options - Whether Tower registration has been confirmed
 */
export async function cacheWorkspaceKeyBlob(blob, options = {}) {
  const fdBlob = toFlightDeckWorkspaceKeyBlob(blob);
  if (!fdBlob?.workspace_owner_npub) return;
  await wsKeysTable().put({
    workspace_owner_npub: fdBlob.workspace_owner_npub,
    user_npub: fdBlob.encrypted_by_npub || '',
    ws_key_npub: fdBlob.ws_key_npub || '',
    ws_key_epoch: fdBlob.ws_key_epoch ?? 1,
    encrypted_blob: fdBlob,
    registered: Boolean(options.registered),
    cached_at: Date.now(),
  });
}

/**
 * Retrieve a cached workspace user key row from IndexedDB.
 * Returns { blob, registered } or null.
 */
export async function getCachedWorkspaceKeyRow(workspaceOwnerNpub, userNpub = '') {
  if (!workspaceOwnerNpub) return null;
  const row = await wsKeysTable().get(workspaceOwnerNpub);
  if (!row?.encrypted_blob) return null;
  const expectedUserNpub = clean(userNpub);
  const cachedUserNpub = firstClean(row.user_npub, row.encrypted_blob.encrypted_by_npub);
  if (expectedUserNpub && cachedUserNpub && cachedUserNpub !== expectedUserNpub) {
    flightDeckLog('warn', 'workspace-key', 'ignoring cached workspace user key for different real user', {
      workspaceOwnerNpub,
      cachedUserNpub,
      userNpub: expectedUserNpub,
    });
    return null;
  }
  return { blob: toFlightDeckWorkspaceKeyBlob(row.encrypted_blob), registered: Boolean(row.registered) };
}

/**
 * Mark a cached workspace user key as registered with Tower.
 */
export async function markCachedWorkspaceKeyRegistered(workspaceOwnerNpub) {
  if (!workspaceOwnerNpub) return;
  const row = await wsKeysTable().get(workspaceOwnerNpub);
  if (row) {
    await wsKeysTable().update(workspaceOwnerNpub, { registered: true });
  }
}

/**
 * Remove a cached workspace user key blob.
 */
export async function removeCachedWorkspaceKeyBlob(workspaceOwnerNpub) {
  if (!workspaceOwnerNpub) return;
  await wsKeysTable().delete(workspaceOwnerNpub);
}

// ---------------------------------------------------------------------------
// Full bootstrap flow
// ---------------------------------------------------------------------------

/**
 * Bootstrap the workspace user key for a workspace.
 *
 * 1. Check IndexedDB for a cached encrypted blob.
 * 2. If found, decrypt with the real signer (one NIP-44 operation).
 * 3. If not found, generate a new key, encrypt, cache, and (optionally) register with Tower.
 *
 * Returns the decrypted key object ready for setActiveWorkspaceKey().
 * The `onRegister` callback is called with the blob when a new key is generated,
 * so the caller can register it with Tower and store on Superbased.
 */
export async function bootstrapWorkspaceSessionKey({
  workspaceOwnerNpub,
  userNpub,
  onRegister,
}) {
  const activeKey = getActiveWorkspaceKey();
  if (activeKey) {
    const activeWorkspaceNpub = firstClean(activeKey.workspaceServiceNpub, activeKey.workspaceOwnerNpub);
    const activeUserNpub = firstClean(activeKey.userNpub);
    if (activeWorkspaceNpub !== clean(workspaceOwnerNpub) || activeUserNpub !== clean(userNpub)) {
      clearActiveWorkspaceKey();
    }
  }

  // 1. Try cached blob
  const cachedRow = await getCachedWorkspaceKeyRow(workspaceOwnerNpub, userNpub);
  if (cachedRow) {
    try {
      const key = await decryptKeyBlob(cachedRow.blob);
      setActiveWorkspaceKey(key, { registered: cachedRow.registered });
      flightDeckLog('info', 'workspace-key', 'decrypted workspace user key from cache', {
        workspaceOwnerNpub,
        wsKeyNpub: key.npub,
        epoch: key.epoch,
        registered: cachedRow.registered,
      });

      // If cached but not yet registered with Tower, retry registration
      if (!cachedRow.registered && typeof onRegister === 'function') {
        try {
          await onRegister(cachedRow.blob, key);
        } catch (error) {
          flightDeckLog('warn', 'workspace-key', 'retry registration failed', {
            workspaceOwnerNpub,
            error: error?.message || String(error),
          });
        }
      }

      return key;
    } catch (error) {
      flightDeckLog('warn', 'workspace-key', 'cached blob decrypt failed, will regenerate', {
        workspaceOwnerNpub,
        error: error?.message || String(error),
      });
      await removeCachedWorkspaceKeyBlob(workspaceOwnerNpub);
    }
  }

  // 2. No cache (or cache was corrupt) — generate new key
  const generated = generateWorkspaceUserKey({
    workspaceServiceNpub: workspaceOwnerNpub,
    userNpub,
  });
  const blob = await createEncryptedKeyBlob({
    wsKeyNsec: generated.nsec,
    wsKeyNpub: generated.workspaceUserKeyNpub,
    wsKeyEpoch: generated.epoch,
    workspaceOwnerNpub,
    userNpub,
  });

  // 3. Cache locally
  await cacheWorkspaceKeyBlob(blob);

  const key = {
    nsec: generated.nsec,
    npub: generated.workspaceUserKeyNpub,
    secret: generated.secret,
    secretHex: generated.secretHex,
    epoch: generated.epoch,
    workspaceOwnerNpub,
    workspaceServiceNpub: workspaceOwnerNpub,
    workspaceUserKeyNpub: generated.workspaceUserKeyNpub,
    userNpub,
  };
  setActiveWorkspaceKey(key);

  flightDeckLog('info', 'workspace-key', 'generated new workspace user key', {
    workspaceOwnerNpub,
    wsKeyNpub: generated.workspaceUserKeyNpub,
  });

  // 4. Notify caller to register with Tower / store on Superbased
  if (typeof onRegister === 'function') {
    try {
      await onRegister(blob, key);
    } catch (error) {
      flightDeckLog('warn', 'workspace-key', 'key registration callback failed', {
        workspaceOwnerNpub,
        error: error?.message || String(error),
      });
    }
  }

  return key;
}
